query Experiences {
    experiences(
        workspaceId: "00000000-0000-0000-0000-000000000002"
        projectId: 1
        jdId: "00000000-0000-0000-0000-000000000003"
        cursor: null
        size: 10
    ) {
        experiences {
            experienceId
            tags
            title
            matchRate
            reason
            project {
                projectId
                name
            }
            contents {
                type
                star {
                    situation
                    task
                    action
                    result
                }
                free {
                    content
                }
            }
        }
        strategy
        cursor {
            nextCursor
            hasNext
        }
    }
}
