query SearchExperiences {
    searchExperiences(
        workspaceId: "00000000-0000-0000-0000-000000000002"
        keyword: "GraphQL"
        cursor: null
        size: 10
    ) {
        experiences {
            experienceId
            tags
            title
            project {
                projectId
                name
            }
            contents {
                type
                star {
                    situation
                    task
                    action
                    result
                }
                free {
                    content
                }
            }
        }
        cursor {
            nextCursor
            hasNext
        }
    }
}
