auth:
  token:
    access-token-ttl: 30m
    refresh-token-ttl: 14d

jwt:
  codec:
    secret: ${JWT_CODEC_SECRET}

crypto:
  secret: ${CRYPTO_SECRET}

---
spring:
  config:
    activate:
      on-profile:
        - local
        - test

jwt:
  codec:
    secret: h2JOe+yl110wJIY0Sz7gma9puyErnVv272wU+021MII=

crypto:
  secret: ${CRYPTO_SECRET:AAECAwQFBgcICQoLDA0ODxAREhMUFRYXGBkaGxwdHh8=}
