create extension if not exists pg_trgm;

create table ai_model_configs_v1 (
    id bigint generated by default as identity,
    ai_model_id bigint not null,
    name varchar(100),
    description text,
    parameters jsonb,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table ai_models_v1 (
    id bigint generated by default as identity,
    name varchar(100) not null,
    vendor varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table experience_project_v1 (
    id bigint generated by default as identity,
    workspace_id bigint not null,
    name varchar(100) not null,
    summary varchar(500) not null,
    start_at date,
    end_at date,
    role varchar(100),
    display_order float(53) not null,
    status varchar(30) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_experience_project_workspace_status_id
    on experience_project_v1 (workspace_id, status, id desc);

create table experience_v1 (
    id bigint generated by default as identity,
    workspace_id bigint not null,
    project_id bigint not null,
    tags jsonb not null,
    title varchar(150) not null,
    contents jsonb not null,
    start_at date,
    end_at date,
    role varchar(100),
    display_order float(53) not null,
    status varchar(30) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_experience_workspace_status_id
    on experience_v1 (workspace_id, status, id desc);

create index idx_experience_workspace_project_status_id
    on experience_v1 (workspace_id, project_id, status, id desc);

create index idx_experience_title_trgm
    on experience_v1 using gin (lower(title) gin_trgm_ops);

create index idx_experience_contents_trgm
    on experience_v1 using gin (lower(cast(contents as varchar)) gin_trgm_ops);

create table jd_experience_recommendation_v1 (
    id bigint generated by default as identity,
    jd_id bigint not null unique,
    items jsonb not null,
    source_signature text not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table jd_v1 (
    id bigint generated by default as identity,
    public_id varchar(50) not null unique,
    workspace_id bigint not null,
    source_url text,
    source_body text,
    company_name varchar(255) not null,
    position_title varchar(255) not null,
    company_intro text not null,
    responsibilities jsonb not null,
    required_experiences jsonb not null,
    preferred_experiences jsonb not null,
    hiring_process jsonb not null,
    core_competencies jsonb not null,
    key_points text not null,
    strategy text not null,
    status varchar(20) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_jd_workspace
    on jd_v1 (workspace_id);

create table notion_connection_v1 (
    id bigint generated by default as identity,
    workspace_id bigint not null,
    notion_workspace_id varchar(100) not null,
    workspace_name varchar(200),
    workspace_icon varchar(1000),
    bot_id varchar(100) not null,
    access_token_encrypted text not null,
    refresh_token_encrypted text not null,
    last_refreshed_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_notion_connection_workspace_notion_workspace_bot unique (workspace_id, notion_workspace_id, bot_id)
);

create index idx_notion_connection_workspace_id
    on notion_connection_v1 (workspace_id, id desc);

create table profile_award_v1 (
    id bigint generated by default as identity,
    profile_id bigint not null,
    display_order integer not null,
    title varchar(100),
    organization varchar(100),
    awarded_at date,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table profile_career_v1 (
    id bigint generated by default as identity,
    profile_id bigint not null,
    display_order integer not null,
    company varchar(100),
    position varchar(100),
    start_at date,
    end_at date,
    description text,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table profile_certification_v1 (
    id bigint generated by default as identity,
    profile_id bigint not null,
    display_order integer not null,
    name varchar(100),
    issuer varchar(100),
    acquired_at date,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table profile_education_v1 (
    id bigint generated by default as identity,
    profile_id bigint not null,
    display_order integer not null,
    school varchar(100),
    major varchar(100),
    degree varchar(30),
    status varchar(30),
    start_at date,
    end_at date,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table profile_language_test_v1 (
    id bigint generated by default as identity,
    profile_id bigint not null,
    display_order integer not null,
    test_name varchar(100),
    score varchar(50),
    acquired_at date,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table profile_skill_v1 (
    id bigint generated by default as identity,
    profile_id bigint not null,
    display_order integer not null,
    name varchar(100),
    level varchar(30),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table profile_v1 (
    id bigint generated by default as identity,
    workspace_id bigint not null unique,
    name_encrypted text,
    phone_encrypted text,
    email_encrypted text,
    core_competency text,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table prompts_v1 (
    id bigint generated by default as identity,
    ai_model_config_id bigint not null,
    type text,
    content text,
    json_schema text,
    deleted_at timestamp(6),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table resume_section_item_v1 (
    id bigint generated by default as identity,
    section_id bigint not null,
    payload_type varchar(30) not null,
    payload jsonb not null,
    display_order float(53) not null,
    visible boolean not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_resume_section_item_section_display_id
    on resume_section_item_v1 (section_id, display_order, id);

create table resume_section_v1 (
    id bigint generated by default as identity,
    resume_id bigint not null,
    type varchar(30) not null,
    display_order float(53) not null,
    visible boolean not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_resume_section_resume_display_id
    on resume_section_v1 (resume_id, display_order, id);

create table resume_v1 (
    id bigint generated by default as identity,
    workspace_id bigint not null,
    target_jd_id bigint,
    template varchar(30) not null,
    status varchar(30) not null,
    core_competency_generated boolean default false not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create index idx_resume_workspace_status_id
    on resume_v1 (workspace_id, status, id desc);

create table user_identity_v1 (
    id bigint generated by default as identity,
    user_id bigint not null,
    provider varchar(30) not null,
    provider_user_id varchar(100) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_user_identity_provider_provider_user_id unique (provider, provider_user_id)
);

create table user_v1 (
    id bigint generated by default as identity,
    public_id varchar(50) not null unique,
    email_encrypted text not null,
    name varchar(50) not null,
    profile_image_url varchar(300),
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table withdrawal_user_v1 (
    id bigint generated by default as identity,
    original_user_id bigint not null,
    public_id varchar(50) not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id)
);

create table workspace_v1 (
    id bigint generated by default as identity,
    public_id varchar(50) not null unique,
    owner_user_id bigint not null,
    created_at timestamp(6),
    updated_at timestamp(6),
    primary key (id),
    constraint uk_workspace_owner_user_id unique (owner_user_id)
);
