query Resumes {
    resumes(
        workspaceId: "00000000-0000-0000-0000-000000000002"
        statuses: [COMPLETED, DRAFT]
    ) {
        resumes {
            resumeId
            targetJd {
                jdId
                sourceUrl
                companyName
                positionTitle
                insight {
                    keyPoints
                    strategy
                }
                status
            }
            template
            status
            createdAt
            updatedAt
        }
        cursor {
            nextCursor
            hasNext
        }
    }
}
