query Resume {
    resume(
        workspaceId: "00000000-0000-0000-0000-000000000002"
        resumeId: 94123123213123123
    ) {
        resumeId
        targetJd {
            jdId
            sourceUrl
            companyName
            positionTitle
            companyIntro
            responsibilities
            requiredExperiences
            preferredExperiences
            hiringProcess
            coreCompetencies
            insight {
                keyPoints
                strategy
            }
            status
            createdAt
        }
        template
        status
        createdAt
        sections {
            sectionId
            type
            displayText
            displayOrder
            visible
            createdAt
            items {
                itemId
                displayOrder
                visible
                createdAt
                payload {
                    basicInfo {
                        name
                        email
                        phone
                        hideContact
                    }
                    coreSkill {
                        content
                    }
                    career {
                        companyName
                        role
                        period {
                            startAt
                            endAt
                        }
                        contents
                    }
                    experience {
                        name
                        role
                        period {
                            startAt
                            endAt
                        }
                        contents
                    }
                    education {
                        schoolName
                        major
                        degree
                        status
                        period {
                            startAt
                            endAt
                        }
                    }
                    award {
                        name
                        organization
                        awardedAt
                    }
                    language {
                        examName
                        scoreOrGrade
                        acquiredAt
                    }
                    certificate {
                        name
                        organization
                        acquiredAt
                    }
                    skill {
                        name
                        level
                    }
                }
            }
        }
    }
}
