@authorizationCode = google-authorization-code
@refreshToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIzMmYwMTJhOS0zZDRmLTQwZDktYWM4MC01YjA0MDRlZGI5NmEiLCJqdGkiOiJiZTQyYTlmNC01YTcwLTQzMmYtYjUzZC0yN2M3YTEyODQ0OGIiLCJpYXQiOjE3ODE2MTczNDQsImV4cCI6MTc4MjgyNjk0NCwidG9rZW5fdHlwZSI6IlJFRlJFU0gifQ.kydzx8dZ4pB6kwTdsmU0O0Km3S27bxF2KyUKw6ozkmU

### Sign up
POST {{host}}/v1/auth/signup
Content-Type: application/json

{
    "provider": "GOOGLE",
    "authorizationCode": "{{authorizationCode}}"
}

### Login
POST {{host}}/v1/auth/login
Content-Type: application/json

{
    "provider": "GOOGLE",
    "authorizationCode": "{{authorizationCode}}"
}

### Refresh access token
POST {{host}}/v1/auth/refresh
Cookie: refresh_token={{refreshToken}}

### Logout
POST {{host}}/v1/auth/logout
Cookie: refresh_token={{refreshToken}}
