@authorizationCode = 4/0AdkVLPyEChTaO40FQVcNIgDDxE-RK4Dye-m5pfmh-d_pfkDkkvqicZoXEmuOvo3tC1rvdA

### Issue test token pair
GET {{host}}/test-tokens

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}


### Login
POST {{host}}/v1/auth/login
Content-Type: application/json

{
    "provider": "GOOGLE",
    "authorizationCode": "{{authorizationCode}}",
    "redirectUri": "http://localhost:3000/google-oauth-code-test-tool.html"
}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
    client.global.set("refreshToken", response.body.result.refreshToken);
%}

### Refresh access token
POST {{host}}/v1/auth/refresh
Cookie: refresh_token={{refreshToken}}

> {%
    client.global.set("accessToken", response.body.result.accessToken);
%}

### Logout
POST {{host}}/v1/auth/logout
Cookie: refresh_token={{refreshToken}}
