@accessToken = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIwMDAwMDAwMC0wMDAwLTAwMDAtMDAwMC0wMDAwMDAwMDAwMDEiLCJqdGkiOiJiOGY2ZWNmYy1mYTYwLTQ0ODMtOGFmNC0xMDJhMjdlNWQ1ZmYiLCJpYXQiOjE3ODE2MjAzNjQsImV4cCI6MTc4MTYyMDM4MCwidG9rZW5fdHlwZSI6IkFDQ0VTUyJ9.jM8y4m5RzjoyrfCpBaBYVGJFjpXu8raimj0liFCq_GA

### Get my user
GET {{host}}/v1/users/me
Authorization: Bearer {{accessToken}}
