spring:
  sql:
    init:
      mode: never
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show_sql: false
        format_sql: false
        use_sql_comments: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        default_batch_fetch_size: 300
    open-in-view: false
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


---
spring.config:
  activate:
    on-profile:
      - local

spring:
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: create-drop
    defer-datasource-initialization: true   # Hibernate가 테이블 생성한 뒤 data.sql 실행
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:jobori;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2-console


---
spring.config:
  activate:
    on-profile:
      - test

spring:
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
        dialect: org.hibernate.dialect.H2Dialect

  datasource:
    url: jdbc:h2:mem:jobori;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
