spring.profiles.default: local
spring.config:
  import:
    - classpath:/rdb.yml
    - classpath:/ai.yml

server:
  port: ${SERVER_PORT:20000}

auth:
  token:
    access-token-ttl: 30m
    refresh-token-ttl: 14d

jwt:
  codec:
    secret: ${JWT_SECRET}

spring:
  mvc:
    servlet:
      path: /api
  graphql:
    http:
      path: /graphql
    graphiql:
      enabled: true
      path: /graphiql


---
spring:
  config:
    activate:
      on-profile: local


jwt:
  codec:
    secret: h2JOe+yl110wJIY0Sz7gma9puyErnVv272wU+021MII=
